### PR TITLE
Initial pack support

### PR DESCRIPTION
**Pull request by hifi**
Threw this together real quick. No delta support yet and the code isn't very clean but it's a start. There's some room for optimization in the reader (buffering) but I think it's pretty fast otherwise.

This also now allows testing against the actual project git repository instead of a separate non-packed repository.

Going to look at the delta compression algo next.

### CODE REVIEW

**Comment by hifi** [comment]
Added delta support based on jGit implementation, can now traverse through big git repositories.

**Comment by mvdkleijn** [comment]
Nice. I've read through the commits and looks good. Would you mind changing the merge target of this PR to the develop branch?

**Comment by hifi** [comment]
If you don't mind, I'll squash it all as well? The first implementation wasn't so good so the history isn't so important.

**Comment by mvdkleijn** [comment]
ok, np

**Comment by hifi** [comment]
Squashed to pr #8

**Pull request closed without merging**
